### ISSUE TITLE
Support for RethinkDB 2.3.x

### ISSUE THREAD

**Issue by ktersius** [mikemintz/rethinkdb-websocket-server#16]
Will you be updating the client and server to support 2.3.x in the future? What would need to be done to update?

I think the following change in the 2.3 driver is breaking it at the moment.

> Disallowed calling r.wait, r.rebalance and r.reconfigure on the global scope to avoid confusing semantics. (#4382)

`TypeError: _rethinkdb2.default.wait is not a function
    at Object.<anonymous> (/home/tersiusk/WebstormProjects/pinkdot/node_modules/rethinkdb-websocket-server/dist/ReqlTermExamples.js:109:32)
`

**Comment by mikemintz** [comment]
@ktersius thank you for reporting this. I fixed this in rethinkdb-websocket-server 0.5.1 with https://github.com/mikemintz/rethinkdb-websocket-server/commit/310b3933b3090397a2f408b4cf8ae0049ffba9f7

The client code should still work without changes.
