### ISSUE TITLE
Proper way to use on Heroku?

### ISSUE THREAD

**Issue by manglav** [mikemintz/rethinkdb-websocket-server#21]
I've been having a lot of trouble deploying this app on heroku and using it in conjunction with the client.  What is the proper way to securely run this in production, with security? I get immediate timeouts when I try to use TLS.

**Comment by mikemintz** [comment]
I don't have much experience with heroku. Are you able to get TLS working in general, e.g. accessing your node.js express routes via https URLs from your browser?

**Comment by manglav** [comment]
I was able to get it working, I had to use port 443. It was a big pain though. TLS with heroku is quit complicated.
